### ISSUE TITLE
./configure doesn't find the PHP embed SAPI  on Debian

### ISSUE THREAD

**Issue by pbiggar** [pbiggar/phc#157]
```
What steps will reproduce the problem?
1.Checkout from either svn or git
2.Install the 
3. run ./configure or ./configure --with-php=/usr
4. install libphp5-embed 5.4.4 from testing

What is the expected output? What do you see instead?

I get a message about the SAPI not being found.

configure:16721: gcc -c -isystem/usr/include/php -isystem/usr/include/php/main -isystem/usr/include/php/TSRM
-isystem/usr/include/php/Zend -g -O2  conftest.c >&5

conftest.c:51:34: error: sapi/embed/php_embed.h: No such file or directory


What version of the product are you using? On what operating system?

Tried the released version, svn trunk, github master and github with the patch for
issue #146 included.

Please provide any additional information below.

When I add a link from /usr/include/php to /usr/include/php5 I get:

 configure:16721: checking for sapi/embed/php_embed.h
configure:16721: gcc -c -isystem/usr/include/php -isystem/usr/include/php/main -isystem/usr/include/php/TSRM
-isystem/usr/include/php/Zend -g -O2  conftest.c >&5
configure:16721: $? = 0
configure:16721: result: yes

However, I still get the missing SAPI message.
```

Original issue reported on code.google.com by `killesreiter` on 2012-08-29 12:16:19

**Comment by pbiggar** [comment]
phc is unlikely to work with php 5.4. Try php 5.2.17 (check out circle.yml for how to build on ubuntu).
